<Project Sdk="Microsoft.NET.Sdk">

  <PropertyGroup>
    <OutputType>WinExe</OutputType>
    <TargetFramework>net8.0-windows</TargetFramework>
    <Nullable>enable</Nullable>
    <ImplicitUsings>enable</ImplicitUsings>
    <UseWPF>true</UseWPF>
    <UseWindowsForms>true</UseWindowsForms> <!-- 开启以使用 NotifyIcon -->
    <ApplicationIcon>app.ico</ApplicationIcon> <!-- 指定编译后的 exe 图标 -->
  </PropertyGroup>

  <ItemGroup>
    <!-- 确保 ico 文件随软件生成 -->
    <None Update="app.ico">
      <CopyToOutputDirectory>PreserveNewest</CopyToOutputDirectory>
    </None>
  </ItemGroup>

</Project>